language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt  

before script:
  - export APP_SETTINGS="testing"
  - export DATABASE_URL="dbname='politico' user='voter' host='127.0.0.1' password='voter'"

script:
  - pytest --cov=app

after_success:
  - coveralls

