language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt  

services:
  - postgresql

before script:
  - export APP_SETTINGS="testing"
  - psql -c "CREATE DATABASE politico;" -U postgres
  - psql -c "ALTER user postgres PASSWORD 'voter';" -U postgres
  - export DATABASE_URL="dbname='politico' user='postgres' host='127.0.0.1' password='voter'"

script:
  - pytest --cov=app

after_success:
  - coveralls

