language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt  

before script:
  - export APP_SETTINGS="testing"

script:
  - pytest --cov=app

after_success:
  - coveralls

